language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t upexya/cici-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true upexya/cici-demo npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "app-name-here"
#   env: "" // see in AWS
#   bucket_name: "" // see in s3 management console
#   bucket_path: "app-name-here"
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: "$AWS_SECRET_KEY"

# # IAM > users > add user > allow programmatic request > attach existing policy > beanstalk > create user
# # copy access key id and secret key, add those in travis env variables
# # AWS_ACCESS_KEY
# # AWS_SECRET_KEY
